import React from 'react';
import Head from 'next/head';

type PropsChildren = {
    children?: any;
}

const Layout = ({children}: PropsChildren) => {
    return (
        <>
            <Head>
                <title>Prueba DocRed</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <script src="https://cdn.tailwindcss.com"></script>
            </Head>

            <div className='bg-gray-200'>

                <main className='mb-12'>
                    {children}
                </main>

            </div>
        </>
    )
}

export default Layout;